#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
.. py:currentmodule:: casinotools.fileformat.casino2.Version

.. moduleauthor:: Hendrix Demers <hendrix.demers@mail.mcgill.ca>

Different versions of the CASINO program.
Internal version taken from the CASINO C++ source code.
External version taken from the CASINO C++ source code and file generated by different version of CASINO.
"""

###############################################################################
# Copyright 2017 Hendrix Demers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

# Standard library modules.

# Third party modules.

# Local modules.

# Globals and constants variables.

# Internal version
VERSION_21 = 21
VERSION_22 = 22
VERSION_23 = 23
VERSION_24 = 24
VERSION_25 = 25
VERSION_26 = 26

VERSION_2040601 = 2040601
VERSION_2050000 = 2050000
VERSION_2050100 = 2050100

UNKNOWN_VERSION = 0
CURRENT_VERSION = VERSION_2050100

# External version
VERSION_2_42 = VERSION_23
VERSION_2_43 = VERSION_24
VERSION_2_44 = VERSION_26
VERSION_2_45 = VERSION_26
VERSION_2_46 = VERSION_2040601
VERSION_2_50 = VERSION_2050000
VERSION_2_51 = VERSION_2050100


class Version(object):
    pass
